# Generated by Django 3.1.6 on 2021-02-16 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('plate_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('capacity', models.IntegerField()),
                ('info', models.CharField(blank=True, max_length=200)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
