# Generated by Django 3.1.5 on 2021-02-15 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ride_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=40)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('vechile', models.CharField(max_length=40)),
                ('number_in_party', models.IntegerField(default=1)),
                ('is_shared', models.BooleanField(default=False)),
                ('number_be_shared', models.IntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('sharer', models.CharField(blank=True, max_length=100, null=True)),
                ('special_require', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
