# Generated by Django 3.1.6 on 2021-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_ride_request_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('driver', 'driver'), ('sharer', 'sharer'), ('admin', 'admin')], max_length=10, null=True),
        ),
    ]
