# Generated by Django 3.1.6 on 2021-02-15 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210215_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride_request',
            old_name='is_shared',
            new_name='is_sharable',
        ),
    ]
