# Generated by Django 3.1.6 on 2021-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='license',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='max_passenger',
            field=models.IntegerField(default=3),
        ),
    ]
