# Generated by Django 3.1.6 on 2021-02-16 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210216_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='license',
            new_name='license_num',
        ),
    ]
